package Ship;


/**
* Ship/_AircraftCarrierStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ship.idl
* 01 Mayýs 2020 Cuma 02:05:32 EET
*/

public class _AircraftCarrierStub extends org.omg.CORBA.portable.ObjectImpl implements Ship.AircraftCarrier
{

  public Ship.Aircraft launch (String name)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("launch", true);
                $out.write_string (name);
                $in = _invoke ($out);
                Ship.Aircraft $result = Ship.AircraftHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return launch (name        );
            } finally {
                _releaseReply ($in);
            }
  } // launch

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Ship/AircraftCarrier:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AircraftCarrierStub
