package Ship;


/**
* Ship/AircraftOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ship.idl
* 01 Mayýs 2020 Cuma 02:05:32 EET
*/

public interface AircraftOperations 
{
  String codeNumber ();
  void run ();
  int fuelCapacity ();
} // interface AircraftOperations
