package Ship;

/**
* Ship/AircraftCarrierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ship.idl
* 01 Mayýs 2020 Cuma 02:05:32 EET
*/

public final class AircraftCarrierHolder implements org.omg.CORBA.portable.Streamable
{
  public Ship.AircraftCarrier value = null;

  public AircraftCarrierHolder ()
  {
  }

  public AircraftCarrierHolder (Ship.AircraftCarrier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Ship.AircraftCarrierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Ship.AircraftCarrierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Ship.AircraftCarrierHelper.type ();
  }

}
