package Ship;


/**
* Ship/AircraftCarrierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ship.idl
* 01 Mayýs 2020 Cuma 02:05:32 EET
*/

public interface AircraftCarrierOperations 
{
  Ship.Aircraft launch (String name);
} // interface AircraftCarrierOperations
