package Ship;


/**
* Ship/AircraftPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ship.idl
* 01 Mayýs 2020 Cuma 02:05:32 EET
*/

public abstract class AircraftPOA extends org.omg.PortableServer.Servant
 implements Ship.AircraftOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("codeNumber", new java.lang.Integer (0));
    _methods.put ("run", new java.lang.Integer (1));
    _methods.put ("_get_fuelCapacity", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Ship/Aircraft/codeNumber
       {
         String $result = null;
         $result = this.codeNumber ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // Ship/Aircraft/run
       {
         this.run ();
         out = $rh.createReply();
         break;
       }

       case 2:  // Ship/Aircraft/_get_fuelCapacity
       {
         int $result = (int)0;
         $result = this.fuelCapacity ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Ship/Aircraft:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Aircraft _this() 
  {
    return AircraftHelper.narrow(
    super._this_object());
  }

  public Aircraft _this(org.omg.CORBA.ORB orb) 
  {
    return AircraftHelper.narrow(
    super._this_object(orb));
  }


} // class AircraftPOA
